name: Build and Deploy to EC2 with Docker Hub

on:
  push:
    branches: [ main ]  # Trigger the workflow on pushes to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Log in to Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image and push it to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: abdarrahmane/slot_calendar:latest

      # Deploy the updated image to your EC2 instance via SSH
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}       # Your EC2 public IP or domain
          username: ${{ secrets.EC2_USER }}     # The SSH username
          key: ${{ secrets.EC2_SSH_KEY }}       # Your private SSH key stored as a secret
          script: |
            # Pull the latest image from Docker Hub
            docker pull abdarrahmane/slot_calendar:latest
            
            # Change directory to where your docker-compose.yml resides
            cd /var/www/python_project/backend_my_slot
            
            # Bring down the currently running containers
            docker-compose down
            
            # Start up containers using the updated image
            docker-compose up -d
