version: "3.8"

services:
  web:
    build:
      context: .              # Use the current folder for Docker context
      dockerfile: Dockerfile  # Dockerfile is in the same folder
    ports:
      - "8000:8000"           # Map port 8000
    volumes:
      - db_data:/app/db          # create a named volum for db
    env_file:                 # Load environment variables from .env
      - .env
volumes:
  db_data: # db volum
