services:
  web:
    image: abdarrahmane/slot_calendar:latest # use pre-built image 
    ports:
      - "8000:8000"           # Map port 8000
    volumes:
      - db_data:/app/db          # create a named volum for db
    env_file:                 # Load environment variables from .env
      - .env
volumes:
  db_data: # db volum
