# Generated by Django 4.1.1 on 2022-09-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availabilities",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start", models.DateTimeField(verbose_name="%Y-%m-%d %h:%m")),
                ("end", models.DateTimeField(verbose_name="%Y-%m-%d  %h:%m")),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservations",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=254)),
                ("start", models.DateTimeField(verbose_name="%Y-%m-%d %h:%m")),
                ("end", models.DateTimeField(verbose_name="%Y-%m-%d %h:%m")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tests",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
            ],
        ),
    ]
