# Generated by Django 5.1.2 on 2025-02-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_my_slot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tests',
            new_name='TestModel',
        ),
    ]
