# Generated by Django 4.1.1 on 2022-09-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availabilities",
            fields=[
                (
                    "availabilitieId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("availabilitieStart", models.CharField(max_length=500)),
                ("availabilitieEnd", models.CharField(max_length=500)),
                ("availabilitieCreatedAt", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Reservations",
            fields=[
                ("resevationId", models.AutoField(primary_key=True, serialize=False)),
                ("reservationTitle", models.CharField(max_length=500)),
                ("reservationEmail", models.CharField(max_length=500)),
                ("reservationStart", models.DateField()),
                ("reservationEnd", models.DateField()),
                ("reservationCreatedAt", models.DateField()),
            ],
        ),
    ]
