# Generated by Django 4.1.1 on 2022-09-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availabilities",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Start", models.DateTimeField(verbose_name="%Y-%m-%d %h:%m")),
                ("End", models.DateTimeField(verbose_name="%Y-%m-%d  %h:%m")),
                ("CreatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservations",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=500)),
                ("Email", models.EmailField(max_length=254)),
                ("Start", models.DateTimeField(verbose_name="%Y-%m-%d %h:%m")),
                ("End", models.DateTimeField(verbose_name="%Y-%m-%d %h:%m")),
                ("CreatedAt", models.DateTimeField(verbose_name="%Y-%m-%d %h:%m")),
            ],
        ),
        migrations.CreateModel(
            name="Tests",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=500)),
            ],
        ),
    ]
