# Generated by Django 4.1.1 on 2022-09-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApiMySlot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="availabilities",
            old_name="availabilitieCreatedAt",
            new_name="CreatedAt",
        ),
        migrations.RenameField(
            model_name="availabilities", old_name="availabilitieEnd", new_name="End",
        ),
        migrations.RenameField(
            model_name="availabilities", old_name="availabilitieId", new_name="Id",
        ),
        migrations.RenameField(
            model_name="availabilities",
            old_name="availabilitieStart",
            new_name="Start",
        ),
        migrations.RenameField(
            model_name="reservations",
            old_name="reservationCreatedAt",
            new_name="CreatedAt",
        ),
        migrations.RenameField(
            model_name="reservations", old_name="reservationEmail", new_name="Email",
        ),
        migrations.RenameField(
            model_name="reservations", old_name="reservationEnd", new_name="End",
        ),
        migrations.RenameField(
            model_name="reservations", old_name="resevationId", new_name="Id",
        ),
        migrations.RenameField(
            model_name="reservations", old_name="reservationStart", new_name="Start",
        ),
        migrations.RenameField(
            model_name="reservations", old_name="reservationTitle", new_name="Title",
        ),
    ]
